title='guiBuilder API documentation'
project='guiBuilder'
format='markdown'

file={
	-- Main dir
	'src/guiBuilderAPI/gui.lua',
	'src/guiBuilderAPI/middleclass.lua',
	'src/guiBuilderAPI/bootstrap.lua',
	'src/guiBuilderAPI/utils.lua',

	-- Display dir
	'src/guiBuilderAPI/display/display.lua',
	'src/guiBuilderAPI/display/connection.lua',

	-- guiObject dir
	'src/guiBuilderAPI/guiObject/listener.lua',
	'src/guiBuilderAPI/guiObject/event.lua',
	'src/guiBuilderAPI/guiObject/position.lua',
	'src/guiBuilderAPI/guiObject/color.lua',
	'src/guiBuilderAPI/guiObject/guiObject.lua',

	-- guiObjects
	'src/guiBuilderAPI/guiObject/guiObjects/JButton.lua',
}